add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold {{colors.primary.default.hex}})"
success_symbol = "[❯](bold {{colors.primary.default.hex}})"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold {{colors.primary.default.hex}}"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic {{colors.primary.default.hex}}"

[git_status]
format     = '[$all_status]($style)'
style      = "{{colors.primary.default.hex}}"
ahead      = "⇡$count "
diverged   = "⇕⇡$ahead_count⇣$behind_count "
behind     = "⇣$count "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
